version: "3.9"
services:
  mongo:
    image: mongo
    volumes:
      - db-data:/var/lib/mongo/data
    ports:
      - 27017:27017
    networks:
      - app
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

      

  backend:
    build:
      context: ./server
      args:
        NODE_ENV: development
    depends_on:
      - mongo
         
    restart: unless-stopped
   
    
    env_file: server/.env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    environment:
      - DB_HOST=mongo
      - DB_USER=root
      - DB_PORT = 27017
      - DB_PASSWORD=example
      - DB_NAME=Hubx
      - NODE_ENV=development  
    command: sh -c 'while ! nc -z mongo 27017; do sleep 1; done && npm run dev'
    ports:
      - 3000:3000
    networks:
      - app
  

  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app
 
networks:
  app:
    driver: bridge

volumes:
  db-data:
 